### ISSUE TITLE
White bar on side of docs

### ISSUE THREAD

**Issue by MarcellPerger1** [pygame/pygameweb#137]
There is a white bar on the side of the docs website when the width is around 1000 pixels. This only happens on the page for the `sprite` module and the page for `examples`:
![image](https://github.com/pygame/pygameweb/assets/102254594/2892fcac-1539-4fa0-a8c6-3fd96965bcc5)

Links:
- https://www.pygame.org/docs/ref/sprite.html
- https://www.pygame.org/docs/ref/examples.html

**Comment by MarcellPerger1** [comment]
This also happens in the html docs in the `pygame.docs` module

**Comment by illume** [comment]
Hrmm. I can't reproduce this.

Maybe it's browser specific (what browser are you using here?),
or it's has been fixed in the meantime?

**Comment by MarcellPerger1** [comment]
I'm using Google Chrome version 116, its still happening on those 2 links.

**Comment by MarcellPerger1** [comment]
### The problem
The problem appears to be caused by this bit of the CSS in `pygame.css`:
```css
.toc td {
    display:block;
    width: 200%;  /* <-- this is the problem */
}
```
The problem is that if the width of the parent is too big (this can happen if the name of the thing is very long), the `width: 200%` can make the `td` element exceed the width of the normal page (even though there's nothing in that extra space), causing the white bar on the right and the bottom scrollbar.
### A potential solution
This could be solved by limiting the width to the size of the viewport using
```css
    width: min(200%, 100vw - 132px);  /* the -132px is to account for the padding on the side */
```
instead of `width: 200%`.

**Comment by MarcellPerger1** [comment]
Actually, this issue might be better in the `pygame/pygame` repo as the [source for the CSS](https://github.com/pygame/pygame/blob/main/docs/reST/themes/classic/static/pygame.css_t#L165-L168) is in that repo and this issue affects `pygame.docs` as well, not just the www.pygame.org website.
